// CBC (Competency Based Curriculum) learning areas and pathway subjects
export const CBC_SUBJECTS = [
  'Mathematics',
  'Advanced Mathematics',
  'English',
  'Kiswahili',
  'Kenyan Sign Language',
  'Integrated Science',
  'General Science',
  'Biology',
  'Chemistry',
  'Physics',
  'History and Citizenship',
  'Geography',
  'Christian Religious Education',
  'Islamic Religious Education',
  'Hindu Religious Education',
  'Business Studies',
  'Computer Science',
  'Agriculture',
  'Home Science',
  'Creative Arts & Sports',
  'Sports and Recreation',
  'Physical Education',
  'Music and Dance',
  'Theatre and Film',
  'Fine Art',
  'Applied Art',
  'Literature in English',
  'Arabic',
  'French',
  'German',
  'Mandarin',
  'Indigenous Languages',
  'Community Service Learning',
  'Life Skills Education',
  'Pre-Technical Studies',
  'Aviation Technology',
  'Building Construction',
  'Electricity',
  'Metalwork',
  'Power Mechanics',
  'Woodwork',
  'Media Technology',
  'Marine and Fisheries Technology',
  'Leather Work',
  'Culinary Arts',
  'Hairdressing and Beauty Therapy',
  'Garment Making and Interior Design',
  'Plumbing and Ceramics',
  'Welding and Fabrication',
  'Tourism and Travel',
  'Social Studies',
  'Religious Education'
];

// Junior and senior secondary learning areas used by CBC schools
export const CBC_LEARNING_AREAS = [
  'Mathematics',
  'English',
  'Kiswahili',
  'Kenyan Sign Language',
  'Integrated Science',
  'Health Education',
  'Agriculture',
  'Business Studies',
  'Computer Science',
  'Home Science',
  'Life Skills Education',
  'Pre-Technical Studies',
  'Social Studies',
  'Religious Education',
  'Creative Arts & Sports',
  'Physical Education',
  'Community Service Learning'
];

export const CBC_PATHWAY_SUBJECTS = [
  'Advanced Mathematics',
  'Biology',
  'Chemistry',
  'Physics',
  'General Science',
  'Agriculture',
  'Computer Science',
  'Home Science',
  'Aviation Technology',
  'Building Construction',
  'Electricity',
  'Metalwork',
  'Power Mechanics',
  'Woodwork',
  'Media Technology',
  'Marine and Fisheries Technology',
  'History and Citizenship',
  'Geography',
  'Christian Religious Education',
  'Islamic Religious Education',
  'Hindu Religious Education',
  'Business Studies',
  'Literature in English',
  'Indigenous Languages',
  'Arabic',
  'French',
  'German',
  'Mandarin',
  'Kenyan Sign Language',
  'Sports and Recreation',
  'Physical Education',
  'Music and Dance',
  'Theatre and Film',
  'Fine Art',
  'Applied Art'
];

// 8-4-4 System Subjects (Form 1-4)
export const EIGHTHFOURTHFOUR_SUBJECTS = [
  'Mathematics',
  'English',
  'Kiswahili',
  'History & Government',
  'Geography',
  'Biology',
  'Chemistry',
  'Physics',
  'Christian Religious Education',
  'Islamic Religious Education',
  'Hindu Religious Education',
  'CRE/IRE/HRE',
  'Agriculture',
  'Business Studies',
  'Home Science',
  'Computer Studies',
  'Arabic',
  'French',
  'German',
  'Kenyan Sign Language',
  'Music',
  'Art & Design',
  'Drawing and Design',
  'Building Construction',
  'Electricity',
  'Metalwork',
  'Woodwork',
  'Power Mechanics',
  'Aviation Technology',
  'Marine Engineering'
];

// Combined list of all subjects (CBC + 8-4-4, with duplicates removed)
export const ALL_SUBJECTS = Array.from(new Set([
  ...CBC_SUBJECTS,
  ...CBC_LEARNING_AREAS,
  ...CBC_PATHWAY_SUBJECTS,
  ...EIGHTHFOURTHFOUR_SUBJECTS
])).sort();

// Grouped subjects for better organization
export const GROUPED_SUBJECTS = {
  'CBC Learning Areas': CBC_LEARNING_AREAS,
  'CBC Pathway Subjects': CBC_PATHWAY_SUBJECTS,
  '8-4-4 Subjects': EIGHTHFOURTHFOUR_SUBJECTS.filter(s => !CBC_SUBJECTS.includes(s))
};

// Subject icons mapping (optional, can be extended)
export const SUBJECT_COLORS = {
  'Mathematics': '#FF6B6B',
  'English': '#4ECDC4',
  'Kiswahili': '#45B7D1',
  'Science': '#FFA07A',
  'Integrated Science': '#FFA07A',
  'General Science': '#FFA07A',
  'Physics': '#FFB347',
  'Chemistry': '#87CEEB',
  'Biology': '#90EE90',
  'History & Government': '#D8BFD8',
  'History and Citizenship': '#D8BFD8',
  'Geography': '#DEB887',
  'Religious Education': '#DDA0DD',
  'Christian Religious Education': '#DDA0DD',
  'Islamic Religious Education': '#DDA0DD',
  'Hindu Religious Education': '#DDA0DD',
  'Computer Science': '#20B2AA',
  'Computer Studies': '#20B2AA',
  'Art & Design': '#FFD700',
  'Creative Arts & Sports': '#FFD700',
  'Music': '#FF69B4',
  'Physical Education': '#00CED1',
  'Business Studies': '#DC143C',
  'Agriculture': '#228B22',
  'Home Science': '#F08080',
  'Building Construction': '#808080',
  'Electricity': '#FFD700',
  'Metalwork': '#A9A9A9',
  'Woodwork': '#8B4513',
  'Aviation Technology': '#87CEEB',
  'Marine Engineering': '#4169E1',
  'French': '#0047AB',
  'German': '#000000',
  'Mandarin': '#FF0000',
  'Kenyan Sign Language': '#DC143C',
  'Indigenous Languages': '#8B4513',
  'Pre-Technical Studies': '#A0522D',
};
