CREATE TABLE IF NOT EXISTS `archived_student_portal_credentials` (
  `id` VARCHAR(191) NOT NULL,
  `admissionNumber` VARCHAR(50) NOT NULL,
  `passwordHash` VARCHAR(255) NOT NULL,
  `originalStudentId` VARCHAR(191) NULL,
  `originalPortalAccountId` VARCHAR(191) NULL,
  `sourceBatchId` VARCHAR(191) NULL,
  `archiveReason` VARCHAR(100) NULL,
  `deletedBy` VARCHAR(191) NULL,
  `firstName` VARCHAR(100) NULL,
  `middleName` VARCHAR(100) NULL,
  `lastName` VARCHAR(100) NULL,
  `fullName` VARCHAR(255) NULL,
  `form` VARCHAR(20) NULL,
  `stream` VARCHAR(50) NULL,
  `email` VARCHAR(100) NULL,
  `parentPhone` VARCHAR(20) NULL,
  `status` VARCHAR(50) NOT NULL DEFAULT 'archived',
  `passwordSetAt` DATETIME(3) NULL,
  `lastLoginAt` DATETIME(3) NULL,
  `archivedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `restoredAt` DATETIME(3) NULL,
  `expiresAt` DATETIME(3) NOT NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `archived_student_portal_credentials_admissionNumber_key` (`admissionNumber`),
  INDEX `archived_student_portal_credentials_admissionNumber_idx` (`admissionNumber`),
  INDEX `archived_student_portal_credentials_sourceBatchId_idx` (`sourceBatchId`),
  INDEX `archived_student_portal_credentials_archivedAt_idx` (`archivedAt`),
  INDEX `archived_student_portal_credentials_expiresAt_idx` (`expiresAt`),
  INDEX `archived_student_portal_credentials_restoredAt_idx` (`restoredAt`)
);
